name: number_fun_facts
description: A Flutter app that displays fun facts for numbers.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  hive: ^1.1.1
  http: ^0.12.0
  path_provider: ^1.5.0
  provider: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
